### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by 84896150** [glennliao/apijson-go-demo#1]
main.go:4:2: no required module provides package github.com/glennliao/apijson-go/config; to add it:
	go get github.com/glennliao/apijson-go/config
main.go:5:2: no required module provides package github.com/glennliao/apijson-go/framework; to add it:
	go get github.com/glennliao/apijson-go/framework
main.go:6:2: no required module provides package github.com/glennliao/apijson-go/framework/handler; to add it:
	go get github.com/glennliao/apijson-go/framework/handler

编译完成，并显示退出代码 1

**Comment by glennliao** [comment]
@84896150 apijson-go 的0.2.0 版本改动调整较大， 然后这个demo库因为近期工作比较多以及apijson-go有一些内容还没确定， 所以现在的demo都还不能用。

**Comment by glennliao** [comment]
这里的用法都还是使用到0.1.0的
